group 'com.khub.plugin_player'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '1.9.22'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
          flatDir {
            dirs 'src/main/libs'
        }
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace 'com.khub.plugin_player'
    compileSdkVersion 35

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdkVersion 21
    }
    lint {
        disable 'InvalidPackage'
    }
}

dependencies {
      implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')
    implementation 'com.google.android.exoplayer:exoplayer:2.14.1'
    implementation 'com.google.ads.interactivemedia.v3:interactivemedia:3.22.3'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "androidx.media:media:1.1.0"
    implementation "com.jakewharton:butterknife:10.0.0"
    implementation "com.pixplicity.easyprefs:EasyPrefs:1.10.0"
    implementation "com.jakewharton.timber:timber:4.7.1"
    implementation "uk.co.chrisjenx:calligraphy:2.2.0"
    implementation(name:'mux-r2.11.1', ext:'aar')
    implementation project(':player')
    implementation project(':khub-common-app')
}
ext {
    minSdkVersion = 21
    compileSdkVersion = 35
    targetSdkVersion = 35
    buildToolsVersion = '34.0.0'
    junitVersion = '4.12'
    gsonVersion = '2.8.0'
    okHttpVersion = '3.14.1'
    timberVersion = '4.7.1'
    retrofitVersion = '2.5.0'
    rxAndroidVersion = '2.1.1'
    rxJavaVersion = '2.2.6'
}
